version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./WebApi.DomainEvents/WebApi.DomainEvents.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./WebApi.DomainEvents/WebApi.DomainEvents.csproj
clone_depth: 1
test_script:
  - cmd: dotnet restore ./Tests.Unit/Tests.Unit.csproj --verbosity m
  - cmd: dotnet test ./Tests.Unit/Tests.Unit.csproj
deploy: off